using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace GoManPTCAccountCreator.Model
{

    public static class CountryHelper
    {
        public static string GetDescription(this Enum value)
        {
            Type type = value.GetType();
            string name = Enum.GetName(type, value);
            if (name != null)
            {
                FieldInfo field = type.GetField(name);
                if (field != null)
                {
                    DescriptionAttribute attr =
                           Attribute.GetCustomAttribute(field,
                             typeof(DescriptionAttribute)) as DescriptionAttribute;
                    if (attr != null)
                    {
                        return attr.Description;
                    }
                }
            }
            return null;
        }

        public static CountryModel ToEnum(this string value)
        {
            return (CountryModel)Enum.Parse(typeof(CountryModel), value, true);
        }
    }



    public enum CountryModel
    {
        [Description("UnitedStates")]
        US,
        [Description("Canada")]
        CA,
        [Description("Afghanistan")]
        AF,
        [Description("Albania")]
        AL,
        [Description("Algeria")]
        DZ,
        [Description("Andorra")]
        AD,
        [Description("Angola")]
        AO,
        [Description("Anguilla")]
        AI,
        [Description("AntiguaandBarbuda")]
        AG,
        [Description("Argentina")]
        AR,
        [Description("Armenia")]
        AM,
        [Description("Aruba")]
        AW,
        [Description("Australia")]
        AU,
        [Description("Austria")]
        AT,
        [Description("Azerbaijan")]
        AZ,
        [Description("Bahamas")]
        BS,
        [Description("Bahrain")]
        BH,
        [Description("Barbados")]
        BB,
        [Description("Belarus")]
        BY,
        [Description("Belgium")]
        BE,
        [Description("Belize")]
        BZ,
        [Description("Benin")]
        BJ,
        [Description("Bolivia")]
        BO,
        [Description("BosniaandHerzegovina")]
        BA,
        [Description("Botswana")]
        BW,
        [Description("Brazil")]
        BR,
        [Description("Bulgaria")]
        BG,
        [Description("BurkinaFaso")]
        BF,
        [Description("Burundi")]
        BI,
        [Description("Cameroon")]
        CM,
        [Description("CaymanIslands")]
        KY,
        [Description("CentralAfricanRepublic")]
        CF,
        [Description("Chad")]
        TD,
        [Description("Chile")]
        CL,
        [Description("China(PRC)")]
        CN,
        [Description("Colombia")]
        CO,
        [Description("Comoros")]
        KM,
        [Description("Congo,DemocraticRepublicofthe")]
        CD,
        [Description("CookIslands")]
        CK,
        [Description("CostaRica")]
        CR,
        [Description("Croatia")]
        HR,
        [Description("Curaçao")]
        CW,
        [Description("Cyprus")]
        CY,
        [Description("CzechRepublic")]
        CZ,
        [Description("Denmark")]
        DK,
        [Description("Djibouti")]
        DJ,
        [Description("Dominica")]
        DM,
        [Description("DominicanRepublic")]
        DO,
        [Description("Ecuador")]
        EC,
        [Description("Egypt")]
        EG,
        [Description("ElSalvador")]
        SV,
        [Description("EquatorialGuinea")]
        GQ,
        [Description("Eritrea")]
        ER,
        [Description("Estonia")]
        EE,
        [Description("Ethiopia")]
        ET,
        [Description("Finland")]
        FI,
        [Description("France")]
        FR,
        [Description("FrenchGuiana")]
        GF,
        [Description("Gabon")]
        GA,
        [Description("Gambia")]
        GM,
        [Description("Georgia")]
        GE,
        [Description("Germany")]
        DE,
        [Description("Ghana")]
        GH,
        [Description("Gibraltar")]
        GI,
        [Description("Greece")]
        GR,
        [Description("Grenada")]
        GD,
        [Description("Guadeloupe")]
        GP,
        [Description("Guam")]
        GU,
        [Description("Guatemala")]
        GT,
        [Description("Guernsey")]
        GG,
        [Description("Guinea-Bissau")]
        GW,
        [Description("Guyana")]
        GY,
        [Description("Haiti")]
        HT,
        [Description("Honduras")]
        HN,
        [Description("HongKong")]
        HK,
        [Description("Hungary")]
        HU,
        [Description("Iceland")]
        IS,
        [Description("India")]
        IN,
        [Description("Indonesia")]
        ID,
        [Description("Ireland")]
        IE,
        [Description("IsleofMan")]
        IM,
        [Description("Israel")]
        IL,
        [Description("Italy")]
        IT,
        [Description("Jamaica")]
        JM,
        [Description("Japan")]
        JP,
        [Description("Jersey")]
        JE,
        [Description("Jordan")]
        JO,
        [Description("Kazakhstan")]
        KZ,
        [Description("Kenya")]
        KE,
        [Description("Kuwait")]
        KW,
        [Description("Latvia")]
        LV,
        [Description("Lebanon")]
        LB,
        [Description("Lesotho")]
        LS,
        [Description("Liechtenstein")]
        LI,
        [Description("Lithuania")]
        LT,
        [Description("Luxembourg")]
        LU,
        [Description("Macedonia(Republicof)")]
        MK,
        [Description("Madagascar")]
        MG,
        [Description("Malawi")]
        MW,
        [Description("Malaysia")]
        MY,
        [Description("Mali")]
        ML,
        [Description("Malta")]
        MT,
        [Description("Martinique")]
        MQ,
        [Description("Mauritania")]
        MR,
        [Description("Mauritius")]
        MU,
        [Description("Mexico")]
        MX,
        [Description("Moldova,Republicof")]
        MD,
        [Description("Monaco")]
        MC,
        [Description("Montenegro")]
        ME,
        [Description("Montserrat")]
        MS,
        [Description("Morocco")]
        MA,
        [Description("Mozambique")]
        MZ,
        [Description("Namibia")]
        NA,
        [Description("Netherlands")]
        NL,
        [Description("NetherlandsAntilles")]
        AN,
        [Description("NewZealand")]
        NZ,
        [Description("Nicaragua")]
        NI,
        [Description("Niger")]
        NE,
        [Description("Nigeria")]
        NG,
        [Description("Norway")]
        NO,
        [Description("Oman")]
        OM,
        [Description("Panama")]
        PA,
        [Description("Paraguay")]
        PY,
        [Description("Peru")]
        PE,
        [Description("Philippines")]
        PH,
        [Description("Poland")]
        PL,
        [Description("Portugal")]
        PT,
        [Description("Qatar")]
        QA,
        [Description("Romania")]
        RO,
        [Description("RussianFederation")]
        RU,
        [Description("Rwanda")]
        RW,
        [Description("SaintKittsandNevis")]
        KN,
        [Description("SaintLucia")]
        LC,
        [Description("SaintVincentandtheGrenadines")]
        VC,
        [Description("SanMarino")]
        SM,
        [Description("SaoTomeandPrincipe")]
        ST,
        [Description("SaudiArabia")]
        SA,
        [Description("Senegal")]
        SN,
        [Description("Serbia")]
        CS,
        [Description("SerbiaandKosovo")]
        RS,
        [Description("Seychelles")]
        SC,
        [Description("SierraLeone")]
        SL,
        [Description("Singapore")]
        SG,
        [Description("SintMaarten")]
        SX,
        [Description("Slovakia(SlovakRepublic)")]
        SK,
        [Description("Slovenia")]
        SI,
        [Description("Somalia")]
        SO,
        [Description("SouthAfrica")]
        ZA,
        [Description("Spain")]
        ES,
        [Description("Sudan")]
        SD,
        [Description("Suriname")]
        SR,
        [Description("Swaziland")]
        SZ,
        [Description("Sweden")]
        SE,
        [Description("Switzerland")]
        CH,
        [Description("Taiwan")]
        TW,
        [Description("Tajikistan")]
        TJ,
        [Description("Tanzania,UnitedRepublicof")]
        TZ,
        [Description("Thailand")]
        TH,
        [Description("Togo")]
        TG,
        [Description("TrinidadandTobago")]
        TT,
        [Description("Tunisia")]
        TN,
        [Description("Turkey")]
        TR,
        [Description("Turkmenistan")]
        TM,
        [Description("TurksandCaicosIslands")]
        TC,
        [Description("Uganda")]
        UG,
        [Description("Ukraine")]
        UA,
        [Description("UnitedArabEmirates")]
        AE,
        [Description("UnitedKingdom(GreatBritain)")]
        GB,
        [Description("Uruguay")]
        UY,
        [Description("Uzbekistan")]
        UZ,
        [Description("VaticanCity")]
        VA,
        [Description("Venezuela")]
        VE,
        [Description("VirginIslands(British)")]
        VG,
        [Description("VirginIslands(U.S.)")]
        VI,
        [Description("Yemen")]
        YE,
        [Description("Zambia")]
        ZM,
        [Description("Zimbabwe")]
        ZW,
    }
}

